# Generated by Django 4.0.4 on 2024-05-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], default='PAYMENT', max_length=10)),
                ('session_url', models.URLField(default='http://127.0.0.1:8000', max_length=1000)),
                ('session_id', models.CharField(default=1, max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='borrowings_service.borrowing')),
            ],
        ),
    ]
