# Generated by Django 4.0.4 on 2024-04-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings_service', '0002_rename_book_id_borrowing_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], default='PAYMENT', max_length=10)),
                ('session_url', models.URLField(max_length=1000)),
                ('session_id', models.CharField(max_length=55)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='borrowings_service.borrowing')),
            ],
        ),
    ]
