# Generated by Django 5.0.3 on 2024-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")], max_length=10
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=0)),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
