version: "2.24.6"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    restart: always
    build:
      context: .
    command: ["celery", "--app=library_service_project", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    depends_on:
      app:
        condition: service_started
    env_file:
      - .env