# Generated by Django 5.0.3 on 2024-04-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
    ]
